### ISSUE TITLE
OACMPCTF3 flame textures issue

### ISSUE THREAD

**Issue by Bishop-333** [NeonKnightOA/oacmpvol1#41]
![shot0033](https://user-images.githubusercontent.com/99912467/162949994-2d4af275-a409-424b-8074-a282bf84dc16.jpg)
![shot0036](https://user-images.githubusercontent.com/99912467/162950032-6bf4f398-01a7-4022-815f-77f6eba553f4.jpg)
![shot0038](https://user-images.githubusercontent.com/99912467/162950058-5f023c24-3439-45fc-b527-3e8de309e3c6.jpg)

**Comment by EddieBrrrock** [comment]
z_oacmp1v4_beta-220411

**Comment by NeonKnightOA** [comment]
Where's the problem? Perhaps I fail to see it.

**Comment by The-Gig** [comment]
I'm not sure either what he's referring to.
Maybe that sort of "bleeding edge" one can spot at the top, looking closely at his first screeshot?
![immagine](https://user-images.githubusercontent.com/23258514/225073269-f13a1bc1-e852-47fa-a61f-a590e3cf5779.png)
It might recall some issue with some OA lights (it was the effect around the lights), I don't remember if they were already fixed or not... I kinda recall some old forum post where someone posted an image that more or less explained how to fix the glitch (by altering the image, like making the layer with the actual effect to not reach the border of the image, or something similar), but I've not been able to find it. _Do you?_ The example showed a tree iirc.

Or maybe he's referring to this part of the flame
![immagine](https://user-images.githubusercontent.com/23258514/225076135-ae00db55-7d1d-4449-9f4c-f904d8425bf0.png)
which is fading in & out instead of moving? Not sure if calling it a glitch...

I don't know, both things probably are not oacmp-specific and so should be fixed in the assets of the main game (looking in Netradiant, Akom used sfx/flameanim_red_pj, sfx/flameanim_blue_pj and sfx/flameanim_red_pj, which are all from oasfx.shader in OA pak0.pk3)?

Anyway, a better explanation by @EddieBrrrock would be useful...

**Comment by NeonKnightOA** [comment]
Indeed. He should give a better explanation of what he meant.

The first pic requires a shader tweak. At best I can create a new one that doesn't have that artifact, but that'll mean adding a new texture and a new shader to the pack.

**Comment by EddieBrrrock** [comment]
Hi ! Yeah sorry for the lack of informations given, it's not a glitch just a small textures issue.
There are a small square box around the flame and mostly the texture is too tall so it applied to the top too and is blinking.
It must have the bottom removed by black texture like done with the "spotlights" in oa.

**Comment by NeonKnightOA** [comment]
I guess I should create sfx with the fixed flame.

**Comment by NeonKnightOA** [comment]
I have enlarged the flames from 56 to 64. That seemed to clean the problem away.

**Comment by NeonKnightOA** [comment]
https://mega.nz/file/bMZkRJBa#J_rUm2nz2SpiMFl6kBY0eMceeCLOJ1PLfnz_-CQRzCw
New test version.
